export const europeanCountries = [
    ["Austria", "AT", "Vienna", "Europe/Brussels"],
    ["Belgium", "BE", "Brussels", "Europe/Brussels"],
    // no data ["Bosnia and Herzegovina", "BA", "Sarajevo", "Europe/Belgrade"],
    ["Bulgaria", "BG", "Sofia", "Europe/Sofia"],
    ["Croatia", "HR", "Zagreb", "Europe/Belgrade"], //strange values
    ["Czech Republic", "CZ", "Prague", "Europe/Prague"],
    ["Denmark", "DK", "Copenhagen", "Europe/Copenhagen"],
    ["Estonia", "EE", "Tallinn", "Europe/Tallinn"],
    ["Finland", "FI", "Helsinki", "Europe/Helsinki"], //strange values
    ["France", "FR", "Paris", "Europe/Paris"],
    ["Germany", "DE", "Berlin", "Europe/Berlin"],
    //very strange ["Greece", "GR", "Athens", "Europe/Athens"],
    ["Hungary", "HU", "Budapest", "Europe/Budapest"],
    ["Ireland", "IE", "Dublin", "Europe/Dublin"],
    ["Italy", "IT", "Rome", "Europe/Rome"],
    //no data ["Kosovo", "XK", "Pristina", "Europe/Belgrade"],
    ["Latvia", "LV", "Riga", "Europe/Riga"],
    ["Lithuania", "LT", "Vilnius", "Europe/Vilnius"],
    ["Luxembourg", "LU", "Luxembourg", "Europe/Luxembourg"],
    // strange average ["Moldova", "MD", "Chisinau", "Europe/Chisinau"],
    // strange values ["Montenegro", "ME", "Podgorica", "Europe/Belgrade"],
    ["Netherlands", "NL", "Amsterdam", "Europe/Amsterdam"],
    // strange forecast["North Macedonia", "MK", "Skopje", "Europe/Belgrade"],
    ["Norway", "NO", "Oslo", "Europe/Oslo"],
    ["Poland", "PL", "Warsaw", "Europe/Warsaw"],
    ["Portugal", "PT", "Lisbon", "Europe/Lisbon"],
    ["Romania", "RO", "Bucharest", "Europe/Bucharest"],
    // strange values ["Serbia", "RS", "Belgrade", "Europe/Belgrade"],
    ["Slovakia", "SK", "Bratislava", "Europe/Bratislava"],
    ["Slovenia", "SI", "Ljubljana", "Europe/Ljubljana"],
    ["Spain", "ES", "Madrid", "Europe/Madrid"],
    ["Sweden", "SE", "Stockholm", "Europe/Stockholm"],
    //nan values["Switzerland", "CH", "Bern", "Europe/Zurich"],
];

export const countryFlags: { [key: string]: string } = {
    'Austria': '🇦🇹',
    'Belgium': '🇧🇪',
    'Bosnia and Herzegovina': '🇧🇦',
    'Bulgaria': '🇧🇬',
    'Croatia': '🇭🇷',
    'Czech Republic': '🇨🇿',
    'Denmark': '🇩🇰',
    'Estonia': '🇪🇪',
    'Finland': '🇫🇮',
    'France': '🇫🇷',
    'Germany': '🇩🇪',
    'Greece': '🇬🇷',
    'Hungary': '🇭🇺',
    'Ireland': '🇮🇪',
    'Italy': '🇮🇹',
    'Kosovo': '🇽🇰',
    'Latvia': '🇱🇻',
    'Lithuania': '🇱🇹',
    'Luxembourg': '🇱🇺',
    'Malta': '🇲🇹',
    'Moldova': '🇲🇩',
    'Montenegro': '🇲🇪',
    'Netherlands': '🇳🇱',
    'North Macedonia': '🇲🇰',
    'Norway': '🇳🇴',
    'Poland': '🇵🇱',
    'Portugal': '🇵🇹',
    'Romania': '🇷🇴',
    'San Marino': '🇸🇲',
    'Serbia': '🇷🇸',
    'Slovakia': '🇸🇰',
    'Slovenia': '🇸🇮',
    'Spain': '🇪🇸',
    'Sweden': '🇸🇪',
    'Switzerland': '🇨🇭',
    'Turkey': '🇹🇷',
    'Ukraine': '🇺🇦',
}
